// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4xmVjAh9L3furudofrQdqP
// Component: ECB77-ndfu
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_func.module.css"; // plasmic-import: 4xmVjAh9L3furudofrQdqP/projectcss
import sty from "./PlasmicNewsList.module.css"; // plasmic-import: ECB77-ndfu/css

export type PlasmicNewsList__VariantMembers = {};

export type PlasmicNewsList__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewsList__VariantsArgs;
export const PlasmicNewsList__VariantProps = new Array<VariantPropType>();

export type PlasmicNewsList__ArgsType = {};
type ArgPropType = keyof PlasmicNewsList__ArgsType;
export const PlasmicNewsList__ArgProps = new Array<ArgPropType>();

export type PlasmicNewsList__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultNewsListProps {
  className?: string;
}

export const defaultNewsList__Args: Partial<PlasmicNewsList__ArgsType> = {};

function PlasmicNewsList__RenderFunc(props: {
  variants: PlasmicNewsList__VariantsArgs;
  args: PlasmicNewsList__ArgsType;
  overrides: PlasmicNewsList__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultNewsList__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Posts here......."}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewsList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewsList__VariantsArgs;
    args?: PlasmicNewsList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNewsList__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNewsList__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNewsList__ArgProps,
      internalVariantPropNames: PlasmicNewsList__VariantProps
    });

    return PlasmicNewsList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewsList";
  } else {
    func.displayName = `PlasmicNewsList.${nodeName}`;
  }
  return func;
}

export const PlasmicNewsList = Object.assign(
  // Top-level PlasmicNewsList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicNewsList
    internalVariantProps: PlasmicNewsList__VariantProps,
    internalArgProps: PlasmicNewsList__ArgProps
  }
);

export default PlasmicNewsList;
/* prettier-ignore-end */
